# pierwszy

In [8]:
print("to jest pierwsza komórka jupyter notebook")
a = 100
print(a)

to jest pierwsza komórka jupyter notebook
100


In [9]:
b = 21.8
print(5*b)

109.0


In [10]:
c = a+b
print(c)

121.8


# To jest ważne narzędzie do projektowania **modeli** i <span style="color:red; font-size:16pt;">wizualizacji</span> AI.

In [21]:
lsztuk = "15"

In [23]:
cena = 288

In [22]:
print("kwota do zapłaty:")
int(lsztuk)*cena

kwota do zapłaty:


3360

# To jest drugie miejsce

In [24]:
import numpy as np

In [25]:
np.zeros(23)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
 0., 0., 0., 0., 0., 0.])

In [26]:
u = np.arange(1,89,2)
u

array([ 1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
 69, 71, 73, 75, 77, 79, 81, 83, 85, 87])

In [27]:
lista = [5,27,68,3.454,889,-8776,0,324,7,27,90,2,2,2,-2]
z = np.array(lista)
z

array([ 5.000e+00, 2.700e+01, 6.800e+01, 3.454e+00, 8.890e+02,
 -8.776e+03, 0.000e+00, 3.240e+02, 7.000e+00, 2.700e+01,
 9.000e+01, 2.000e+00, 2.000e+00, 2.000e+00, -2.000e+00])

In [28]:
print(f"typ lista -> {type(lista)}")
print(f"typ z -> {type(z)}")

typ lista -> <class 'list'>
typ z -> <class 'numpy.ndarray'>


In [29]:
t = np.linspace(0,10,num=5)
t

array([ 0. , 2.5, 5. , 7.5, 10. ])

In [30]:
mc_x = np.array([[2,5],[6,8]])
mc_y = np.array([[11,56],[103,71]])
mc_x

array([[2, 5],
 [6, 8]])

In [31]:
mc_z = mc_x * mc_y
mc_z

array([[ 22, 280],
 [618, 568]])

In [32]:
mc_z[mc_z<299]

array([ 22, 280])

# drugi